[1]
input = """
1 0 0 0 0 0 2 2 1
0 0 3 0 0 0 0 1 4
"""

output = """
Yes
"""

[2]
input = """
0 0 0 0 0 0 0 1 0
1 0 0 0 0 0 0 4 0
"""

output = """
No
"""

[3]
input = """
2 0 0 0 0 0 0 0 0
1 0 0 0 0 0 0 0 2
"""

output = """
No
"""

