workspace:
  ongoing_dir: problems # Default: ""
  archive_dir: solved
filetype:
  py:
    language: "python3"
    filename: main.py # Defailt: main.{filetype}
    run: "python3 $file"
  cpp:
    language: "c++17"
    filename: main.cpp
    compile: "g++ -std=c++17 -O2 -DLOCAL -Wall -Wno-sign-compare $file -o a.out"
    run: "./a.out"
    after: rm -rf a.out
    manifest_files:
      - compile_flags.txt
  rs:
    language: "rust2021"
    filename: main.rs # Default: main.{filetype}
    source_dir: src
    compile: "rustc $file -o main"
    run: "./main"
    after: rm -rf ./main
    manifest_files:
      - Cargo.toml
