general:
  selenium_browser: chrome
  default_filetype: cpp
  editor_command: nvim -o
workspace:
  ongoing_dir: problems
  archive_dir: solved
filetype:
  cpp:
    language: "c++17"
    main: main.cpp
    source_templates: 
      - main.cpp
    root_templates:
      - compile_flags.txt
    compile: g++ -std=c++17 -O2 -DLOCAL -Wall -Wno-sign-compare $file -o a.out
    run: "./a.out"
    after: rm -rf a.out
