[1]
input = """
2 1 1 1
"""

output = """
6
"""

[2]
input = """
2 2 1 0
"""

output = """
3
"""

[3]
input = """
3 2 2 1
"""

output = """
0
"""

[4]
input = """
3 2 2 2
"""

output = """
36
"""

[5]
input = """
8 1 15 20
"""

output = """
197121
"""

